root: true
env:
    browser: true
    worker: true
    es2024: true
parser: "@typescript-eslint/parser"
parserOptions:
    project:
        - "./engine/tsconfig.json"
plugins:
    - "@typescript-eslint"
    - "optional-params"
    - "import"
ignorePatterns:
    - "node_modules"
    - "build"
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
    eol-last:
        - error
    object-curly-spacing:
        - error
        - always
    comma-dangle:
        - error
        - always-multiline
    no-trailing-spaces:
        - error
    no-multiple-empty-lines:
        - error
        - max: 1
    space-infix-ops:
        - error
    space-in-parens:
        - error
        - never
    space-before-function-paren:
        - error
        - never
    keyword-spacing:
        - error
    space-before-blocks:
        - error
    newline-before-return:
        - error
    no-multi-spaces:
        - error
    optional-params/max-optional-params:
        - error
        - 1
    import/no-cycle:
        - error
    '@typescript-eslint/explicit-function-return-type':
        - error
    '@typescript-eslint/explicit-module-boundary-types':
        - error
    '@typescript-eslint/no-explicit-any':
        - error
    '@typescript-eslint/explicit-member-accessibility':
        - error
    '@typescript-eslint/no-empty-interface':
        - off
